### ISSUE TITLE
如果只是解析aml文件 然后传递给webview的话 何不直接让webview加载 然后将对应的功能注入进去呢 比如支付

### ISSUE THREAD

**Issue by fangkyi03** [zhaomenghuan/flutter-mini-program#4]

**Comment by zhaomenghuan** [comment]
其实这个项目初衷是探索用 Flutter 构建小程序 UI 层，突破小程序基于 WebView 不太好处理同层渲染的问题，最近看微信团队和美团都有类似的方案。Flutter 在架构上和浏览器(或者说 WebView)很类似，但是相对于浏览器更轻量和可控。

**Comment by fangkyi03** [comment]
你项目我跑不起来 报错
![image](https://user-images.githubusercontent.com/30390014/67998374-40db0b80-fc93-11e9-829e-94be2baba0fe.png)
最近看了一篇阿里的支付宝小程序架构
他们的setData是跑在web worker上的 跟ui不在同一个线程上 不知道你这个是这样做的吗
原本想看看你项目的 但是跑不起来就没继续看了

**Comment by zhaomenghuan** [comment]
@fangkyi03 这个很久没有看，可能版本有问题，周末打算重新整一下，把 JSC 换成基于 flutter ffi 方案，参考：https://github.com/xinfeng-tech/flutter_jsc

**Comment by fangkyi03** [comment]
不如使用mxflutter

**Comment by fangkyi03** [comment]
搞了半天 终于算是跑起来了 
总之各种问题 注释了好几处代码才跑起来 
1.cacheImage版本与flutter不兼容 会报错 升级最新版本
2.去除plugin 因为ios会报找不到flutterMiniplugin.h
3.注释
![image](https://user-images.githubusercontent.com/30390014/68086738-df30c200-fe89-11e9-8408-ae7194275340.png)
![image](https://user-images.githubusercontent.com/30390014/68086743-e526a300-fe89-11e9-8b2e-e1c7ae672d83.png)
4.
![image](https://user-images.githubusercontent.com/30390014/68086800-5fefbe00-fe8a-11e9-81c4-ee603b063af3.png)
因为注释了第二步以后 所有的script 无法执行 所以还得把这个注释了 否者会触发你的parseFail 然后渲染一个白屏
5.注释app.init 修改成
![image](https://user-images.githubusercontent.com/30390014/68086811-7dbd2300-fe8a-11e9-9946-7b84eecb9211.png)
上面哪些操作修改完以后 index页面的确是可以正常显示了 但是无法进行路由跳转 只能这样处理一下

真心不容易 一波三折
